### ISSUE TITLE
Mettre en place la gestion du debug

### ISSUE THREAD

**Issue by Tanin69** [GdC-Framework/Cache_Cash#13]
Gérer le debug avec une ou des fonctions transversales. Doit permettre de gérer plusieurs niveaux de debug et de faire la sortie soit à l'écran (systemChat) soit dans le rpt, soit dans les deux.

Sinon, on intègre les macros de debug de CBA dont le système est tout prêt (sauf sortie systemChat)

**Comment by Tanin69** [comment]
Les macros de CBA, c'est quand même un marteau pilon pour écraser une mouche. Je vais m'en inspirer pour faire une version très simplifiée.
Mais je vous préviens : si vous me demandez d'ajouter UNE feature, on bascule sur les macros de cba :-D

**Comment by Morbakos** [comment]
On peut utiliser les macro CBAAAAA ? :P
